### ISSUE TITLE
[BUG] ERROR AwsUtils: The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by liangjun-jiang** [aws-samples/aws-emr-advisor#7]
**Describe the bug**
After the reports is generated, I saw this error when it tried to write the report to the specified s3 location. 

24/12/06 15:08:46 INFO HtmlReport: Saving html report in /tmp/emr-insights.1733497714724.html
24/12/06 15:08:46 INFO HtmlReport: Saving html report in s3://my-s3-bucket/logs/emr-insights/emr-insights.1733497714724.html
24/12/06 15:08:46 ERROR AwsUtils: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: S3, Status Code: 403, Request ID: 2B6DQAFVEE53196F, Extended Request ID: jqWVJorStQFyxliAWBENifNDzQVQ6noesqEaWHKV7DMOJJoRlDoeFJ9HwR/qKx49TvzkrMc7+e25pKnytgKiGnZBgj8zbTF39usYsh1z/tE=)
24/12/06 15:08:46 INFO HtmlReport: To access the report, open the following url in your browser:

... redacted 
**To Reproduce**
EMR release (e.g. emr-7.3.0) : 
1. emr-7.3.0 with spark pi event log

**Expected behavior**
should not see this error since the user/me didn't do any S3 request. 

**Screenshots**
n/a

**Additional context**

**Comment by ripani-aws** [comment]
From the logs I see that you specified `my-s3-bucket` as the S3 output of the report (this is done by passing the --bucket parameter in the command), so S3 permissions are required to store the report in the bucket path. If you don't want to use a bucket and only store a local report, do not specify the `--bucket` parameter. Closing this issue.

**Comment by liangjun-jiang** [comment]
@ripani-aws : the reason I used `my-s3-bucket` in the posted log is for masking out the sensitive information. I did put my real bucket name in place. 
But I can give it a try without specifying a `bucket` parameter.
